python run.py \
--data_dir ./data \
--output_dir output/all/roberta-base \
--train_tasks ufet tacred maven \
--eval_tasks ufet tacred maven fewrel \
--do_train \
--eval_during_training \
--logging_epochs 10 \
--save_epochs 10 \
--num_train_epochs 100 \
--per_gpu_train_batch_size 128 \
--model_name_or_path roberta-base \